### ISSUE TITLE
WMM2020?

### ISSUE THREAD

**Issue by r2evans** [wfrierson/wmm#1]
Is there a plan for adding the WMM2020 model? I believe it was released early last year, and supports through 2025.

Thanks!

**Comment by wfrierson** [comment]
Sure, I can add it. How soon do you need it?

**Comment by r2evans** [comment]
I can't demand anything with urgency. I'm working on a project over the next few weeks that is currently just scraping magvar from NOAA. I'd prefer something offline (and not relying on having to scrape, no formal API), so this package popped in my searches. (I'm not even certain how different the results are expected to be from WMM2015, tbh.)

Thanks!

**Comment by wfrierson** [comment]
Ok that's reasonable. This week is rough, but next week I could start on it. Good question on whether the results have changed much from the last coefficients! *shrug*

**Comment by wfrierson** [comment]
Update: The ice storms in the US delayed the update. I'll start it this coming week.

**Comment by wfrierson** [comment]
@r2evans , I've run into an issue where my calculations are not agreeing with the WMM in the blackout zone near the poles. I'm still troubleshooting this. All other test values agree within 0.1 nT. If you don't need field values near the blackout zone, I can push the development branch with the latest coefficients. You can use devtools to install this version. I will wait to update on CRAN until the blackout zone issue is fixed.

**Comment by r2evans** [comment]
I'm not using coordinates that extreme, to be honest, but please don't kill yourself to make this happen quickly. My uses are mostly within +/- 50 latitude. (I do some analytics for car racing, and ... I don't know of many car races in the blackout zones, assuming https://www.ngdc.noaa.gov/geomag/WMM/limit.shtml.)

If you release it, I'll likely give it a go with the clear "contract" that I'll refrain from using your model for racing in those zones.

Jokes aside, are the differences mathematic? That is, I'm assuming that you are implementing the math according to the papers/standards, so what kind of differences are we talking about? Are your tests in the "rest of the world" within ... how many degrees declination?

(Don't take these questions as criticism, they're intended for me to understand the variance in the calculations. In my current use, I'm looking for accuracy, not precision. That is, if the WMM standard says -7.015467 and your model is returning -7.015, I think my needs will be unaffected. Heck, in my days in aviation, if I could keep within 1 degree I was pretty happy. :-)

Looking at the WMM blackout zone images in the link above made me think of something kinda funny. In my days in aviation, I tended to stay under 1.2Mach, peaking 1.5Mach or so a few times. A joke with the SR-71 Blackbird is something along the lines of *"you've never been lost until you've been lost at Mach 3"*. I can relate. Now imagine ... they may be flying far and fast enough where they might actually be able to "sense" significant swings in magvar, given ideal location. Funny side point, sorry to distract.

Thanks for looking into this!

**Comment by wfrierson** [comment]
No criticism taken & thank you for your patience! Just unexpected output.

I suspect the issue here is catastrophic cancellation of floats. The field values disagree when latitude is above 87° N/S. I'll try a few formulations and see if it fixes it.

**Comment by wfrierson** [comment]
Fixed it! The issue was using recursion relations for associated Legendre polynomials that accrued larger and larger errors for higher orders when latitude > +/-86°. I didn't realize there's a direct, closed-form equation that's equally fast to compute.

Let me clean up the code and push the updates to the wmm2020 branch. You can use that in the meantime while I go through the CRAN update process.

Thanks for your patience!

**Comment by wfrierson** [comment]
@r2evans, I've pushed the updates for WMM2020 and found a way to speed it up by ~7x. It'll be a bit before the update goes to CRAN, but feel free to pull from master here.

Let me know if you have any questions or find any issues.

**Comment by r2evans** [comment]
I'll check shortly, thank you!
